/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDictionaryRouteImport } from './routes/api/public/dictionary'
import { Route as ApiPublicPomodoroLiveRouteImport } from './routes/api/public/pomodoro-live'
import { Route as ApiPublicDbSyncRouteImport } from './routes/api/public/db-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDictionaryRoute = ApiPublicDictionaryRouteImport.update({
  id: '/api/public/dictionary',
  path: '/api/public/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPomodoroLiveRoute = ApiPublicPomodoroLiveRouteImport.update({
  id: '/api/public/pomodoro-live',
  path: '/api/public/pomodoro-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDbSyncRoute = ApiPublicDbSyncRouteImport.update({
  id: '/api/public/db-sync',
  path: '/api/public/db-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/dictionary': typeof ApiPublicDictionaryRoute
  '/api/public/pomodoro-live': typeof ApiPublicPomodoroLiveRoute
  '/api/public/db-sync': typeof ApiPublicDbSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/dictionary': typeof ApiPublicDictionaryRoute
  '/api/public/pomodoro-live': typeof ApiPublicPomodoroLiveRoute
  '/api/public/db-sync': typeof ApiPublicDbSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/dictionary': typeof ApiPublicDictionaryRoute
  '/api/public/pomodoro-live': typeof ApiPublicPomodoroLiveRoute
  '/api/public/db-sync': typeof ApiPublicDbSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/dictionary' | '/api/public/pomodoro-live' | '/api/public/db-sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/dictionary' | '/api/public/pomodoro-live' | '/api/public/db-sync'
  id: '__root__' | '/' | '/api/public/dictionary' | '/api/public/pomodoro-live' | '/api/public/db-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDictionaryRoute: typeof ApiPublicDictionaryRoute
  ApiPublicPomodoroLiveRoute: typeof ApiPublicPomodoroLiveRoute
  ApiPublicDbSyncRoute: typeof ApiPublicDbSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dictionary': {
      id: '/api/public/dictionary'
      path: '/api/public/dictionary'
      fullPath: '/api/public/dictionary'
      preLoaderRoute: typeof ApiPublicDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pomodoro-live': {
      id: '/api/public/pomodoro-live'
      path: '/api/public/pomodoro-live'
      fullPath: '/api/public/pomodoro-live'
      preLoaderRoute: typeof ApiPublicPomodoroLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/db-sync': {
      id: '/api/public/db-sync'
      path: '/api/public/db-sync'
      fullPath: '/api/public/db-sync'
      preLoaderRoute: typeof ApiPublicDbSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDictionaryRoute: ApiPublicDictionaryRoute,
  ApiPublicPomodoroLiveRoute: ApiPublicPomodoroLiveRoute,
  ApiPublicDbSyncRoute: ApiPublicDbSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
